PAY-7200: Front end changes to Calculate the AMOUNT DUE and OVERPAYME…
hmcts/ccpay-web-component pull request #362
Opened 2024-07-10 13:20 UTC by Thor-tech-of-metal

PAY-7200: Front end changes to Calculate the AMOUNT DUE and OVERPAYMENTS for ( Issue refund and Remission-Refunds)
           [PAY-7200] (https://tools.hmcts.net/jira/browse/PAY-7200).

2024-07-10 14:19 UTC, Thor-tech-of-metal commented on projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
> +
Nooooo I need to remove it. console.log("aca2 !!!"+ refund.refund_status.name);

2024-07-10 14:21 UTC, Thor-tech-of-metal commented on projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
> +
DONE al console  removed

2024-07-10 14:24 UTC, davejones74 approved these changes

2024-07-10 14:28 UTC, Ollie-Smith approved these changes
reviewed

2024-07-16 15:09 UTC, davejones74 submitted a review, later dismissed

2024-07-16 15:17 UTC, danlysiak submitted a review, later dismissed

2024-08-01 14:32 UTC, Ollie-Smith submitted a review, later dismissed
A coding wizard here.  Amazing!

2024-08-02 11:42 UTC, davejones74 submitted a review, later dismissed

2024-08-12 10:26 UTC, chrisworthcgi submitted a review, later dismissed

2024-08-13 08:21 UTC, davejones74 requested changes

2024-08-13 12:00 UTC, Thor-tech-of-metal commented on projects/payment-lib/src/lib/components/case-transactions/case-transactions.component.ts
>            this.calculateOverpayment();
DONE

2024-08-13 12:43 UTC, davejones74 approved these changes

2024-08-13 13:22 UTC, chrisworthcgi approved these changes

2024-08-20 13:57 UTC, Ollie-Smith submitted a review, later dismissed
reviewed

2024-08-20 15:46 UTC, davejones74 commented on projects/payment-lib/src/lib/components/payment-view/payment-view.component.ts
> +  isTheCurrentRefundInProcessForThisFee(fee: IFee): boolean{
You have the same method defined twice in payment-vew.component.ts and service-request.component.ts? 

It's using the paymentLibComponent, so this needs to be added to the payment-lib.component.ts as you've duplicated the same code. 

You can then call :
paymentLibComponent.isTheCurrentRefundInProcessForThisFee(fee);

2024-08-21 13:56 UTC, davejones74 approved these changes

2024-08-21 13:57 UTC, Ollie-Smith reviewed
reviewed

2024-08-21 13:58 UTC, Ollie-Smith approved these changes
reviewed

2024-09-09 10:14 UTC, davejones74 approved these changes

2024-09-09 10:20 UTC, chrisworthcgi approved these changes

2024-09-09 10:21 UTC, merged